packages/composables/src/getters/_utils.ts, packages/composables/src/getters/productGetters.ts, packages/theme/pages/Product.vue, yarn.lock
[#5](https://github.com/vuestorefront/shopify/issues/5)  
closes #5 
Made required modifications(eg.product.attributeslist => product.options) and fetched the available variations and attributes to the single product page
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)
**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change
=> variable product attributes on single page

README.md, packages/composables/src/getters/_utils.ts, packages/composables/src/useCart/currentCart.ts, packages/theme/components/AppHeader.vue, packages/theme/components/CartSidebar.vue, packages/theme/components/LoginModal.vue, packages/theme/pages/Category.vue, packages/theme/pages/Product.vue
[#9 ](https://github.com/vuestorefront/shopify/issues/9)  
closes #9  
Resolved the My Cart sidebar toggle panel
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)
**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change
=> Fixed sidebars

.gitignore, packages/composables/src/getters/_utils.ts, packages/composables/src/getters/productGetters.ts, packages/theme/pages/Category.vue, packages/theme/pages/Product.vue
[#12  ](https://github.com/vuestorefront/shopify/issues/12)  
closes #12   
Resolved the My Cart sidebar toggle panel
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)
**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change
=> Fixed conflicts on passing product(s) to getters

package.json
closes  
Added yarn start command to run the production build
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)
**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change
=> Updated package.json for yarn start

packages/api-client/package.json, packages/composables/package.json
Moved js-cookie dependencies to dependencies to make cookies working on SSR
=> updated dependencies

packages/composables/src/index.ts
reverted createApiClient import
=> reverted createApiClient import

packages/composables/src/useCart/index.ts
Resolved cart id not stored bug on the server. The issue was on a server to store the cart id on SSR
=> Resolved cart id not stored bug on server

packages/theme/pages/MyAccount/MyProfile.vue
Fix on login my-profile userData not rendering
=> Fix on login my-profile userData not rendering

.eslintignore, .eslintrc.json, packages/theme/components/AppFooter.vue, packages/theme/components/LocaleSelector.vue
Fixed props alt missing on SfImage
=> Fixed props alt missing on SfImage

packages/theme/components/InstagramFeed.vue, packages/theme/components/MobileStoreBanner.vue, packages/theme/pages/Category.vue, packages/theme/pages/Product.vue
Fixed alt props missing on component SfImage in PDP & theme components
=> Fixed alt props for PDP

packages/theme/pages/Product.vue
fixed main image not loading because of Lazyhydrate on the product detail page
=> fixed main image not loading - PDP

packages/composables/src/getters/cartGetters.ts, packages/theme/components/CartSidebar.vue
Make customer redirected to Shopify checkout, instead of in-app checkout
=> Skipped in app checkout

packages/theme/pages/Product.vue
Fixed bug of showing HTML as string on PDP
=> Fixed HTML description - PDP

package.json, packages/api-client/package.json, packages/theme/package.json
Moved PWA & isomorphic-fetch dependencies to the theme root
=> Moved PWA & isomorphic-fetch deps to theme

packages/api-client/package.json, packages/api-client/src/api/signIn/index.ts, packages/composables/package.json, packages/composables/src/useCart/index.ts, packages/theme/components/CartSidebar.vue, packages/theme/components/LoginModal.vue, packages/theme/composables/index.ts, packages/theme/composables/useUiHelpers/index.ts, packages/theme/composables/useUiNotification/index.ts, packages/theme/composables/useUiState.ts, packages/theme/middleware/authenticated.js, packages/theme/package.json, packages/theme/pages/Category.vue, packages/theme/pages/MyAccount.vue, yarn.lock
- Packages updated to 2.3.3
- Implemented middleware
- Added notifications
=> Upgraded to 2.3.3 & implemented middle ware

packages/api-client/package.json, packages/composables/package.json, packages/theme/package.json
Updated to `@vue-storefront/shopify` to `0.1.2-rc.1`
=> Updated to shopify 0.1.2-rc.1

packages/api-client/package.json, packages/composables/package.json, packages/composables/src/getters/productGetters.ts, packages/theme/layouts/error.vue, packages/theme/package.json, packages/theme/pages/Product.vue
-  Implemented variant based information PDP
=> Implemented variant based information PDP

docs/guide/getting-started.md
broken link in a documentation
=> fix: broken link in documentation

.eslintrc.js, packages/composables/package.json, packages/composables/src/useCart/index.ts, packages/theme/components/AppHeader.vue, packages/theme/components/BottomNavigation.vue, packages/theme/components/CartSidebar.vue, packages/theme/composables/index.ts, packages/theme/middleware.config.js, packages/theme/nuxt.config.js, packages/theme/pages/Category.vue, packages/theme/pages/MyAccount.vue, packages/theme/pages/MyAccount/AdressBook.vue, packages/theme/pages/Product.vue, yarn.lock
There's an instance where the Vue is complaining about multiple instance of Vue
The change is to revert back the ordering and ignore eslint rule on import/order and import/first
=> fix: multi vue instance

packages/api-client/package.json, packages/composables/package.json, packages/theme/composables/index.ts, packages/theme/composables/useUiHelpers/index.ts, packages/theme/composables/useUiState.ts, packages/theme/nuxt.config.js, packages/theme/package.json, yarn.lock
Fix multiple instance of Vue
Reverted some of the necessary import order to make it work again
=> fix: multiple instance of vue

docs/guide/checkout.md, docs/guide/use-product.md, docs/guide/use-user-order.md, packages/api-client/package.json, packages/composables/package.json, packages/composables/src/index.ts, packages/composables/src/useCart/index.ts, packages/composables/src/useCheckout/index.ts, packages/composables/src/useStore/index.ts, packages/composables/src/useWishlist/index.ts, packages/theme/components/AppHeader.vue, packages/theme/components/CartSidebar.vue, packages/theme/components/FeaturedProduct.vue, packages/theme/components/LocaleSelector.vue, packages/theme/components/LoginModal.vue, packages/theme/components/MyAccount/BillingAddressForm.vue, packages/theme/composables/useUiHelpers/index.ts, packages/theme/composables/useUiNotification/index.ts, packages/theme/composables/useUiState.ts, packages/theme/nuxt.config.js, packages/theme/package.json, packages/theme/pages/Category.vue, packages/theme/pages/Home.vue, packages/theme/pages/MyAccount.vue, packages/theme/pages/MyAccount/AdressBook.vue, packages/theme/pages/MyAccount/MyProfile.vue, packages/theme/pages/MyAccount/OrderHistory.vue, packages/theme/pages/Product.vue, packages/theme/pages/TermsAndConditions.vue, yarn.lock
update storefront/core to 2.5.0
=> chore: update core

packages/api-client/package.json, packages/theme/nuxt.config.js
Adding ```storefront-ui``` module to transpile option of nuxt.config.js file to remediate compilation issue
(https://github.com/vuestorefront/shopify/issues/95)
- Package documentation notes that the reference herein is required....see reference at bottom of page here - https://docs.storefrontui.io/?path=/story/getting-started-installation--page
- Seeking to ensure that the clone package will build properly
- Validated successful compilation
- Validated that app loads and renders with no browser console issues
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] My code follows the code style of this project.
- [X ] I have read the **CONTRIBUTING** document.
- [ X] All new and existing tests passed.
=> fix: remediation of compilation issue of theme - Bug/95

packages/theme/package.json
=> chore: bump core-js version

.gitignore, package.json, packages/theme/README.md
this added a simple run script for generating template with the vsf cli working version
=> chore: added generate template script

package.json
Upgrade a rollup plugin dependency to remediate issue with transitive dependency
https://github.com/vuestorefront/shopify/issues/107
Improve health of the project
- Built local packages
- Validated app startup
=> chore: Upgrade rollup-plugin-typescript2 Resolves: https://github.com/vuestorefront/shopify/issues/107

packages/api-client/src/index.server.ts, packages/api-client/src/next/api/index.ts, packages/api-client/src/next/api/product/index.ts, packages/api-client/src/next/api/product/search.ts, packages/api-client/src/next/types/api/endpoints.ts, packages/api-client/src/next/types/api/index.ts, packages/api-client/src/next/types/context/index.ts, packages/api-client/src/next/types/index.ts, packages/composables/src/index.ts, packages/composables/src/types/index.ts, packages/composables/src/useSearch/index.ts, packages/composables/src/useSearch/params.ts, packages/composables/tsconfig.json
This is a feature where it could search through products from Shopify API by the term
This feature is added to prepare for the mega menu search feature UI
=> feat: added useSearch composables

.gitignore, docs/guide/use-search.md, packages/api-client/src/next/api/product/search.ts, packages/api-client/src/next/index.ts, packages/composables/src/useSearch/params.ts
Documentation update for use search
=> docs: update use search

packages/api-client/src/api/fetchOrders/index.ts, packages/composables/src/useUser/index.ts
=> refactor: fetchorder original total for the refunded orders

packages/api-client/package.json, packages/api-client/src/api/fetchOrders/index.ts, packages/composables/package.json, packages/composables/src/useUser/index.ts, packages/theme/package.json
=> Forgot password error

.github/workflows/assign-pr-to-author.yml, .github/workflows/test.yml
=> chore: updated unit testing included shopify-apollo

packages/composables/src/useCart/index.ts
Closes #138 
This changes will add feature to accepts array of product and quantity to the cart
=> feat: added new way to add items to cart as an array

packages/api-client/package.json, packages/api-client/src/next.ts, packages/apollo/package.json, packages/composables/package.json, packages/composables/src/getters/searchGetters.ts, packages/composables/src/helpers/internals/convertProductsGqlToLocal.ts, packages/composables/src/useFacet/index.ts, packages/theme/package.json
Fixed missing apollo package types
=> fix: apollo missing types

packages/theme/components/CartSidebar.vue
This is a fix for the errors encountered when opening cart sidebar and checkout
Tested locally and will be tested with spot checks once deployed
=> fix: cart sidebar checkout error

packages/theme/nuxt.config.js, packages/theme/package.json, yarn.lock
This is an additional feature to generate sitemap automatically by using @nuxtjs/sitemap
#135
=> feat: add generate sitemap

.prettierrc, packages/composables/src/getters/productGetters.ts, packages/theme/lang/de.js, packages/theme/lang/en.js, packages/theme/pages/Product.vue
Fixed #206 
This a maintenance work on making the Shopify storefront adhere to the standard design of the storefront UI
Tested in local with post check on deployed version
=> chore: update on product unavailable ui

packages/composables/src/helpers/internals/enhanceProduct.ts, packages/theme/pages/Product.vue
Fixed #205
Maintenance work to make the product title still shows the title instead of only the variant
=> chore: update rules on product title

packages/apollo/src/api/getBlog.ts, packages/apollo/src/api/getBlogs.ts, packages/apollo/src/api/getPage.ts, packages/apollo/src/api/index.ts, packages/composables/__tests__/useContent.spec.ts, packages/composables/src/types/ContentType.ts, packages/composables/src/types/UseContentParams.ts, packages/composables/src/useContent/index.ts
Closes #179 
This will add functionality to composable and apollo client to fetch list of blogs or blog
=> chore: update the articles query function in api client

packages/apollo/src/api/getArticles.ts, packages/theme/layouts/default.vue
Closes #181 
This will add a blog page where the list of articles is shown
=> feat: create a page for displaying blog posts

packages/apollo/src/api/getArticles.ts, packages/apollo/src/api/getBlogs.ts, packages/theme/layouts/default.vue, packages/theme/pages/blogs/_handle.vue
This will add functionality in switching blogs/categories reload the current page
=> feat: a list of blogs/articles page

packages/apollo/src/api/getArticles.ts, packages/composables/src/getters/_utils.ts, packages/composables/src/getters/articleGetters.ts, packages/composables/src/getters/index.ts, packages/composables/src/useContent/index.ts, packages/theme/enums/SortBy.ts, packages/theme/pages/blogs/_handle.vue
Closes #182 
This will add features of sorting, paging, and per page limit of articles shown.
=> feat: connect the components with the composable logics

packages/apollo/src/api/getArticle.ts, packages/apollo/src/api/getArticles.ts, packages/apollo/src/api/index.ts, packages/composables/src/useContent/index.ts, packages/theme/composables/useUiHelpers/index.ts, packages/theme/lang/de.js, packages/theme/lang/en.js, packages/theme/pages/articles/_handle.vue, packages/theme/pages/blogs/_handle.vue
Closes #182 
This will add article page that is accessible via /articles/{handle}?id={id}
=> chore: added article page

packages/theme/pages/Category.vue
Closes #261 
This will disable add to cart button in the horizontal view of the Product List Page
=> fix(category): disable add to cart button on horizontal view

packages/api-client/src/api/getProduct/index.ts, packages/theme/components/RelatedProducts.vue, packages/theme/pages/Category.vue
Closes #259 
This will now fix disable the add to cart whenever it has no stock left
=> fix(RelatedProducts): add to cart on match it with section

packages/theme/components/AppHeader.vue
Closes #267 
This will fix the styling issue whereby it adds active classes and styling on current select page
=> fix(appheader): header menu item remains active

packages/theme/package.json
=> chore(general): modern=client

packages/api-client/package.json, packages/composables/package.json, packages/theme/nuxt.config.js
=> Middleware config

packages/composables/src/getters/facetGetters.ts, packages/composables/src/helpers/internals/enhanceProduct.ts
=> fix: valid fallback from getter methods

packages/theme/components/AppHeader.vue
=> fix(appheader): search drawer close on navigation

packages/composables/src/useUser/index.ts, packages/theme/pages/MyAccount.vue, packages/theme/pages/MyAccount/MyProfile.vue
Closes #173 
This is now a refactor on some components use and styling on my profile page
=> fix(my-account): account menu not working

packages/apollo/src/api/availableCountries.ts, packages/apollo/src/api/index.ts, packages/composables/src/index.ts, packages/composables/src/useAvailableCountries/index.ts, packages/theme/components/LocaleSelector.vue, packages/theme/modules/cms/pages/blogs/_handle.vue
=> feat: language select with currency

packages/theme/components/AppHeader.vue, packages/theme/pages/Category.vue
=> fix(appheader): hide search on route change

packages/theme/components/SearchResults.vue
=> fix(searchresults): odd spacing

packages/api-client/package.json, packages/apollo/package.json, packages/composables/package.json, packages/theme/package.json
=> chore: shopify version updated to 1.1.1

packages/api-client/package.json, packages/apollo/package.json, packages/composables/package.json
=> chore: updated to 1.1.2

.github/workflows/docs-deployment.yaml
=> fix: docker publish

packages/api-client/package.json, packages/apollo/package.json, packages/composables/package.json, packages/composables/src/useCart/index.ts, packages/theme/package.json
=> fix(resetCart): reset cart on successful order placement
